include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    dead_code: warning
    missing_required_param: error
